import test from 'node:test';
import assert from 'node:assert/strict';
import {
  parseBurikoWaveBoxHeader,
  BurikoWaveBoxError,
} from '../dist/engines/buriko/native/audio/wavebox-header.js';
import {
  createBurikoCustomWaveBoxDecoder,
  decodeBurikoAdpcm4Sample,
  decodeBurikoHfAdpcm8Sample,
} from '../dist/engines/buriko/native/audio/wavebox-codecs.js';

function wave(codec, payload, fields = {}) {
  const output = new Uint8Array(64 + payload.length),
    header = new DataView(output.buffer);
  for (const [offset, value] of Object.entries({
    0: 64,
    4: 0x20207762,
    12: 4,
    16: 44100,
    20: 1,
    36: 127,
    44: 127,
    48: codec,
    60: 7,
    ...fields,
  }))
    header.setUint32(Number(offset), value, true);
  output.set(payload, 64);
  return output;
}
function samples(bytes) {
  assert.equal(bytes.length % 2, 0);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  return Array.from({length: bytes.length / 2}, (_, index) => view.getInt16(index * 2, true));
}
function huffmanPayload(symbolBytes, rootValue) {
  const output = new Uint8Array(0x408 + symbolBytes.length),
    tree = new DataView(output.buffer, 8, 0x400);
  if (rootValue !== undefined) tree.setUint32(0, rootValue, true);
  else {
    let nextNode = 256;
    const node = (depth, prefix) => {
      if (depth === 0) return prefix;
      const index = nextNode++,
        zero = node(depth - 1, prefix * 2),
        one = node(depth - 1, prefix * 2 + 1);
      tree.setInt16((index - 256) * 4 + 4, zero, true);
      tree.setInt16((index - 256) * 4 + 6, one, true);
      return index;
    };
    tree.setUint32(0, node(8, 0), true);
  }
  output.set(symbolBytes, 0x408);
  return output;
}

test('WaveBox parser preserves native selector precedence, header fields, and raw checkpoint words', () => {
  assert.throws(
    () => parseBurikoWaveBoxHeader(new Uint8Array(63)),
    (error) => error instanceof BurikoWaveBoxError && error.nativeCode === 14,
  );
  assert.throws(
    () => parseBurikoWaveBoxHeader(wave(9, [], {4: 0})),
    (error) => error.nativeCode === 14,
  );
  assert.throws(
    () => parseBurikoWaveBoxHeader(wave(0, [], {4: 0})),
    (error) => error.nativeCode === 0x11000001,
  );
  const source = wave(3, [], {
    0: 96,
    8: 99,
    12: 10,
    16: 48000,
    20: 2,
    24: 2,
    28: 5,
    32: 0xffffffff,
    36: 999,
    40: 77,
    44: 200,
    52: 13,
    56: 29,
    60: 11,
  });
  const h = parseBurikoWaveBoxHeader(source);
  source[0] = 0;
  assert.equal(h.raw.length, 64);
  assert.equal(h.resetDataOffset, 96);
  assert.equal(h.raw[0], 96);
  assert.deepEqual(
    [
      h.field08,
      h.sourceFrameCount,
      h.sampleRate,
      h.channels,
      h.loopEnabled,
      h.loopStartFrame,
      h.field34,
      h.huffmanLoopBitOffset,
      h.hfAdpcmShiftParameter,
    ],
    [99, 10, 48000, 2, 2, 5, 13, 29, 11],
  );
  assert.deepEqual(h.loopLeft, {predictor: 0xffffffff, step: 999});
  assert.deepEqual(h.loopRight, {predictor: 77, step: 200});
});

test('ADPCM arithmetic matches independent native leaf execution boundary vectors', () => {
  // Generated by executing the verified arithmetic leaf instructions on x86-64; no asset inputs.
  for (const [kind, code, predictor, step, arg, output, nextPredictor, nextStep] of [
    [0, 8, 0, 127, 0, 65521, 4294967281, 127],
    [0, 7, 0, 127, 0, 238, 238, 303],
    [0, 7, 0, 24576, 0, 32767, 46080, 24576],
    [0, 15, 0, 24576, 0, 32768, 4294921216, 24576],
    [0, 7, 2147483647, 127, 0, 32768, 2147483885, 303],
    [0, 8, 2147483647, 24576, 0, 32767, 2147480575, 21888],
    [1, 120, 0, 127, 7, 956, 956, 5435],
    [1, 106, 0, 127, 1, 6762, 6762, 5435],
    [1, 44, 0, 127, 11, 88, 88, 127],
    [1, 200, 0, 127, 7, 64961, 4294966721, 2996],
    [1, 128, 2147483648, 4096, 15, 32767, 2147483640, 3648],
    [1, 4, 2147483648, 4096, 3, 32768, 2147488256, 4928],
  ]) {
    const state = {predictor, step};
    const sample =
      kind === 0
        ? decodeBurikoAdpcm4Sample(code, state)
        : decodeBurikoHfAdpcm8Sample(code, state, arg);
    assert.equal(sample & 65535, output);
    assert.deepEqual(state, {predictor: nextPredictor, step: nextStep});
  }
  assert.throws(
    () => decodeBurikoHfAdpcm8Sample(0, {predictor: 0, step: 127}, 61),
    /division by zero/,
  );
});

test('PCM16 retains odd short reads and applies binary64 gain before signed clipping', () => {
  const d = createBurikoCustomWaveBoxDecoder(wave(1, [0x10, 0x27, 0xf0, 0xd8, 0x7f], {12: 3}), {
    gain: 0.5,
  });
  assert.deepEqual(d.readFrameBytes(3), Uint8Array.of(0x88, 0x13, 0x78, 0xec, 0x7f));
  assert.equal(d.decodedFramePosition, 2);
  assert.equal(d.outputBits, 16);
  assert.equal(d.readFrameBytes(1).length, 0);
  d.reset();
  assert.deepEqual(samples(d.readFrameBytes(2)), [5000, -5000]);
  const clipped = createBurikoCustomWaveBoxDecoder(wave(1, [0xff, 0x7f, 0x00, 0x80], {12: 2}), {
    gain: 2,
  });
  assert.deepEqual(samples(clipped.readFrameBytes(2)), [32767, -32768]);
  const overflow = createBurikoCustomWaveBoxDecoder(wave(1, [1, 0], {12: 1}), {gain: Infinity});
  assert.deepEqual(samples(overflow.readFrameBytes(1)), [-32768]);
});

test('PCM16 initial cursor is 64 while reset and loop use the declared data offset', () => {
  const d = createBurikoCustomWaveBoxDecoder(
    wave(1, [1, 0, 2, 0, 3, 0, 4, 0], {0: 68, 12: 2, 28: 1}),
    {gain: 1},
  );
  assert.deepEqual(samples(d.readFrameBytes(2)), [1, 2]);
  d.reset();
  assert.deepEqual(samples(d.readFrameBytes(2)), [3, 4]);
  d.restartLoop();
  assert.equal(d.decodedFramePosition, 1);
  assert.deepEqual(samples(d.readFrameBytes(1)), [4]);
  d.overrideLoop(2);
  assert.equal(d.loopEnabled, 2);
  assert.equal(d.loopStartFrame, 0);
  assert.equal(d.header.loopStartFrame, 1);
  d.restartLoop();
  assert.deepEqual(samples(d.readFrameBytes(1)), [3]);
});

test('ADPCM4 decodes low nibble first and stereo predictors remain independent', () => {
  const mono = createBurikoCustomWaveBoxDecoder(wave(0, [0x10, 0x32]), {gain: 1});
  assert.deepEqual(samples(mono.readFrameBytes(4)), [15, 62, 141, 252]);
  mono.reset();
  assert.deepEqual(samples(mono.readFrameBytes(4)), [15, 62, 141, 252]);
  const stereo = createBurikoCustomWaveBoxDecoder(wave(0, [0x10, 0x32], {12: 2, 20: 2}), {gain: 1});
  assert.deepEqual(samples(stereo.readFrameBytes(2)), [15, 47, 94, 158]);
});

test('ADPCM4 odd mono calls preserve pending output and native lower frame counter discrepancy', () => {
  const d = createBurikoCustomWaveBoxDecoder(wave(0, [0x10, 0x32, 0x54], {12: 5}), {gain: 1});
  assert.deepEqual(samples(d.readFrameBytes(3)), [15, 62, 141]);
  assert.equal(d.decodedFramePosition, 3);
  assert.deepEqual(samples(d.readFrameBytes(3)), [252, 394, 603]);
  assert.equal(d.decodedFramePosition, 5);
  assert.equal(d.readFrameBytes(1).length, 0);
});

test('ADPCM4 loop checkpoint restores unclamped state and its odd pending sample bypasses gain', () => {
  const d = createBurikoCustomWaveBoxDecoder(
    wave(0, [0x70, 0x00], {12: 3, 28: 1, 32: 100, 36: 127}),
    {gain: 0.5},
  );
  d.restartLoop();
  assert.deepEqual(samples(d.readFrameBytes(1)), [338]);
  assert.equal(d.decodedFramePosition, 1);
  assert.deepEqual(samples(d.readFrameBytes(2)), [187, 204]);
});

test('HFADPCM8 Huffman bits are MSB-first and symbols feed alternating channel predictors', () => {
  const payload = huffmanPayload(Uint8Array.of(0, 128, 1, 129));
  const d = createBurikoCustomWaveBoxDecoder(wave(2, payload, {12: 2, 20: 2}), {gain: 1});
  assert.deepEqual(samples(d.readFrameBytes(2)), [3, -3, 14, -14]);
  d.reset();
  assert.deepEqual(samples(d.readFrameBytes(2)), [3, -3, 14, -14]);
});

test('HFADPCM8 loop bit offset is retained and a leaf-only tree consumes no encoded bits', () => {
  const d = createBurikoCustomWaveBoxDecoder(
    wave(2, huffmanPayload(Uint8Array.of(0xa5, 0x80)), {12: 1, 56: 3, 60: 11}),
    {gain: 1},
  );
  d.restartLoop();
  assert.deepEqual(samples(d.readFrameBytes(1)), [88]);
  const constant = createBurikoCustomWaveBoxDecoder(
    wave(2, huffmanPayload(new Uint8Array(), 0), {12: 3}),
    {gain: 1},
  );
  assert.deepEqual(samples(constant.readFrameBytes(3)), [3, 6, 9]);
});

test('HFADPCM8 refill retains partial byte offsets across 1024-byte boundaries and read calls', () => {
  const bits = '01011'.repeat(2000),
    encoded = new Uint8Array(bits.length / 8);
  for (let index = 0; index < bits.length; index++)
    if (bits[index] === '1') encoded[index >>> 3] |= 0x80 >>> (index & 7);
  const payload = new Uint8Array(0x408 + encoded.length),
    tree = new DataView(payload.buffer, 8, 0x400);
  tree.setUint32(0, 256, true);
  tree.setInt16(4, 0, true);
  tree.setInt16(6, 257, true);
  tree.setInt16(8, 128, true);
  tree.setInt16(10, 3, true);
  payload.set(encoded, 0x408);
  const resource = wave(2, payload, {12: 3000, 20: 2});
  const whole = createBurikoCustomWaveBoxDecoder(resource, {gain: 1}).readFrameBytes(3000);
  assert.deepEqual(samples(whole.subarray(0, 12)), [3, -3, 30, 0, 27, 27]);
  const chunked = createBurikoCustomWaveBoxDecoder(resource, {gain: 1}),
    parts = [];
  for (const count of [1, 4, 511, 35, 1200, 1249]) parts.push(...chunked.readFrameBytes(count));
  assert.deepEqual(Uint8Array.from(parts), whole);
  assert.equal(chunked.decodedFramePosition, 3000);
});

test('WaveBox short encoded reads preserve native stored bytes and distinguish unwritten memory', () => {
  const d = createBurikoCustomWaveBoxDecoder(wave(0, [0], {12: 4}), {gain: 1});
  assert.deepEqual(samples(d.readFrameBytes(2)), [15, 30]);
  assert.deepEqual(samples(d.readFrameBytes(2)), [45, 60]);
  const empty = createBurikoCustomWaveBoxDecoder(wave(0, [], {12: 2}), {gain: 1});
  assert.throws(() => empty.readFrameBytes(2), /unwritten native allocation/);
  const shortTree = new Uint8Array(12); // Eight ignored bytes and a known root leaf; other tree bytes stay unwritten.
  const hf = createBurikoCustomWaveBoxDecoder(wave(2, shortTree, {12: 1}), {gain: 1});
  assert.deepEqual(samples(hf.readFrameBytes(1)), [3]);
  const zeroChannels = createBurikoCustomWaveBoxDecoder(wave(1, [], {20: 0}), {gain: 1});
  assert.throws(() => zeroChannels.readFrameBytes(0), /division by zero/);
});
