// Generated by the production build. Scope also isolates sibling Pages projects.
const cachePrefix = `vn-web-engine:${self.registration.scope}:`;
const cacheName = `${cachePrefix}__BUILD_REVISION__`;
const files = /* __PRECACHE_FILES__ */ [];
const appUrls = new Set(files.map((file) => new URL(file, self.registration.scope).href));

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(cacheName)
      .then((cache) =>
        cache.addAll([...appUrls].map((url) => new Request(url, {cache: 'reload'}))),
      ),
  );
  // Keep the browser's waiting phase: a game may have unsaved progress and lazy
  // imports from the previous build. Never skipWaiting or reload a running game.
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith(cachePrefix) && name !== cacheName)
            .map((name) => caches.delete(name)),
        ),
      ),
  );
  // Do not claim pages loaded before this worker; their modules may be older.
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || request.headers.has('range')) return;
  const url = new URL(request.url);
  // Directory and diagnostic-query navigations use the same cached HTML shell.
  if (request.mode === 'navigate') {
    if (url.href.split('?')[0] === self.registration.scope) url.pathname += 'index.html';
    url.search = '';
  }
  url.hash = '';
  // Only built website files are cached. Local installations, saves, arbitrary
  // network requests and debug streaming endpoints keep their existing owners.
  if (!appUrls.has(url.href)) return;
  event.respondWith(
    caches.open(cacheName).then(async (cache) => (await cache.match(url.href)) ?? fetch(request)),
  );
});
