// Generated by the production build. Scope also isolates sibling Pages projects.
const cachePrefix = `vn-web-engine:${self.registration.scope}:`;
const cacheName = `${cachePrefix}__BUILD_REVISION__`;
const files = /* __PRECACHE_FILES__ */ [];
const appUrls = new Set(files.map((file) => new URL(file, self.registration.scope).href));

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(cacheName)
      .then((cache) =>
        cache.addAll([...appUrls].map((url) => new Request(url, {cache: 'reload'}))),
      ),
  );
  // Keep the browser's waiting phase: a game may have unsaved progress and lazy
  // imports from the previous build. Pages show an update notice instead, and
  // only the user's Reload choice activates this build early.
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'activate-update') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      // An early activation leaves other tabs running the previous build. Keep
      // its cache for their lazy imports until an activation finds at most the
      // reloading tab open.
      const windows = await self.clients.matchAll({type: 'window', includeUncontrolled: true});
      if (windows.length > 1) return;
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith(cachePrefix) && name !== cacheName)
          .map((name) => caches.delete(name)),
      );
    })(),
  );
  // Do not claim pages loaded before this worker; their modules may be older.
});

/** Serves a file of a previous build to a tab that still runs that build. */
async function matchPreviousBuild(url) {
  for (const name of await caches.keys()) {
    if (!name.startsWith(cachePrefix) || name === cacheName) continue;
    const response = await (await caches.open(name)).match(url);
    if (response) return response;
  }
  return undefined;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || request.headers.has('range')) return;
  const url = new URL(request.url);
  // Directory and diagnostic-query navigations use the same cached HTML shell.
  if (request.mode === 'navigate') {
    if (url.href.split('?')[0] === self.registration.scope) url.pathname += 'index.html';
    url.search = '';
  }
  url.hash = '';
  if (appUrls.has(url.href)) {
    event.respondWith(
      caches.open(cacheName).then(async (cache) => (await cache.match(url.href)) ?? fetch(request)),
    );
    return;
  }
  // Emitted build files have content-hashed names under assets/.
  if (request.mode !== 'navigate' && url.href.startsWith(`${self.registration.scope}assets/`)) {
    event.respondWith(matchPreviousBuild(url.href).then((response) => response ?? fetch(request)));
  }
  // Everything else (local installations, saves, arbitrary network requests and
  // debug streaming endpoints) keeps its existing owner.
});
